
services:
  qbittorrent:
    container_name: qbittorrent
    image: hotio/qbittorrent:latest
    restart: unless-stopped
    ports:
      - ${WEBUI_PORT}:8080
      - ${CONNECTION_PORT}:6881
      - ${CONNECTION_PORT}:6881/udp
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1  # Optional, if you want to use ipv6, remove this line. If you keep this line, make sure there is no ipv6 in your wg0.conf.
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}:/config:rw
      - ${DATA_DIR}:/data/torrents:rw
