services:
   jdownloader:
    image: jaymoulin/jdownloader:${JD_VERSION:-latest}
    container_name: jdownloader
    restart: unless-stopped
    volumes:
        - ${JD_CONFIG_PATH}:/opt/JDownloader/app/cfg
        - ${JD_DOWNLOAD_PATH}:/opt/JDownloader/Downloads
        - ${JD_EXTENSIONS_PATH}:/opt/JDownloader/app/extensions
        - /etc/localtime:/etc/localtime:ro #optional
    environment: 
        MYJD_USER: ${MYJD_USER}
        MYJD_PASSWORD: ${MYJD_PASSWORD}
        MYJD_DEVICE_NAME: ${MYJD_DEVICE_NAME}
        XDG_DOWNLOAD_DIR: /opt/JDownloader/Downloads
    ports:
        - 3129:3129
