services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-26.1.2}
    container_name: keycloak
    command: ["start"]
    ports:
      - "${KEYCLOAK_HTTP_PORT:-8080}:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
      - KC_LOG_LEVEL=${KC_LOG_LEVEL:-info}
      - KC_HOSTNAME=${KC_HOSTNAME:-localhost}
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_postgres:5432/keycloak
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
  keycloak_postgres:
    container_name: keycloak_postgres
    image: postgres:${POSTGRES_VERSION:-17.4}
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
volumes:
  keycloak_postgres_data:
